# Generated by Django 2.0.3 on 2018-05-30 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_Read',
            field=models.BooleanField(default=False),
        ),
    ]
