# Generated by Django 2.0.3 on 2018-05-31 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userinfo_unread_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notice',
        ),
    ]
