# Generated by Django 2.0.5 on 2018-06-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='profile',
            field=models.ImageField(default='defa.jpg', upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='unread_count',
            field=models.IntegerField(default=0),
        ),
    ]
