# Generated by Django 2.0.5 on 2018-06-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180605_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='profile',
            field=models.ImageField(default='img/defa.jpg', upload_to='img/'),
        ),
    ]
