# Generated by Django 2.0.3 on 2018-06-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180605_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='profile',
            field=models.ImageField(default='img/default.jpg', upload_to='img/'),
        ),
    ]
