# Generated by Django 2.0.3 on 2018-06-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20180606_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='profile',
            field=models.ImageField(default='img/user/default.jpg', upload_to='img/user'),
        ),
    ]
