# Generated by Django 2.0.3 on 2018-06-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20180607_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='profile',
            field=models.ImageField(default='user/img/default.jpg', upload_to='user/img'),
        ),
    ]
