# Generated by Django 2.0.3 on 2018-06-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lenotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='profile',
            field=models.ImageField(default='img/group/default.jpg', upload_to='img/group'),
        ),
    ]
