# Generated by Django 2.0.5 on 2018-06-15 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lenotes', '0003_auto_20180607_2306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imgele',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idname', models.CharField(max_length=40)),
                ('img', models.ImageField(upload_to='diary/img')),
                ('zindex', models.IntegerField()),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('belong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lenotes.Diary')),
            ],
        ),
        migrations.CreateModel(
            name='Textele',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idname', models.CharField(max_length=40)),
                ('content', models.TextField(default='Input something please')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('fontsize', models.IntegerField()),
                ('fontcolor', models.CharField(max_length=20)),
                ('belong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lenotes.Diary')),
            ],
        ),
    ]
