# Generated by Django 2.0.5 on 2018-06-15 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lenotes', '0004_imgele_textele'),
    ]

    operations = [
        migrations.AddField(
            model_name='textele',
            name='zindex',
            field=models.IntegerField(default=999),
        ),
        migrations.AlterField(
            model_name='imgele',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='imgele',
            name='y',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='imgele',
            name='zindex',
            field=models.IntegerField(default=999),
        ),
        migrations.AlterField(
            model_name='textele',
            name='fontcolor',
            field=models.CharField(default='red', max_length=20),
        ),
        migrations.AlterField(
            model_name='textele',
            name='fontsize',
            field=models.IntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='textele',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='textele',
            name='y',
            field=models.IntegerField(default=0),
        ),
    ]
