# Generated by Django 2.0.5 on 2018-06-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lenotes', '0005_auto_20180615_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='imgele',
            name='h',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='imgele',
            name='w',
            field=models.IntegerField(default=30),
        ),
    ]
