# Generated by Django 2.0.3 on 2018-06-19 22:39

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('lenotes', '0006_auto_20180615_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='content',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
