# Generated by Django 2.0.3 on 2018-06-19 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lenotes', '0007_auto_20180619_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='name',
        ),
    ]
