# Generated by Django 2.0.3 on 2018-06-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lenotes', '0009_auto_20180620_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='diary_log',
            field=models.TextField(default=''),
        ),
    ]
