# Generated by Django 2.0.6 on 2018-06-21 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lenotes', '0011_auto_20180621_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='diary_log',
            field=models.TextField(default='2018-06-21 22:24:52.242321  Create diary'),
        ),
    ]
