# Generated by Django 2.0.6 on 2018-06-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lenotes', '0012_auto_20180621_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='diary_log',
            field=models.TextField(default='2018-06-22 09:37:58.876593  Create diary'),
        ),
    ]
