# Generated by Django 2.0.5 on 2018-06-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lenotes', '0013_auto_20180622_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='diary_log',
            field=models.TextField(default='2018-06-30 13:45:13.292516  Create diary'),
        ),
        migrations.AlterField(
            model_name='imgele',
            name='h',
            field=models.FloatField(default=300),
        ),
        migrations.AlterField(
            model_name='imgele',
            name='w',
            field=models.FloatField(default=300),
        ),
        migrations.AlterField(
            model_name='imgele',
            name='x',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='imgele',
            name='y',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='textele',
            name='fontcolor',
            field=models.CharField(default='black', max_length=20),
        ),
        migrations.AlterField(
            model_name='textele',
            name='x',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='textele',
            name='y',
            field=models.FloatField(default=0),
        ),
    ]
